### PR TITLE
Add CDN info to the Readme

### PR DESCRIPTION
**Pull request by limonte**

### CODE REVIEW

**Comment by sarcadass** [comment]
It's nice to make this lib available in a CDN 😃.
But the version is still the 1.0.31.
Are the new versions updated automatically, or should it be done manually on their GitHub repo?

**Comment by limonte** [comment]
It should update automatically. Let's wait next granim.js release and see. I believe it's about some caching issue here.

**Comment by M-arcus** [comment]
I requested it (https://github.com/cdnjs/cdnjs/issues/9046) on cdnjs and it got added.
Is it ok, if you add it in your PR?

**Comment by limonte** [comment]
Sure :+1:

**Pull request closed without merging**
