### PR TITLE
if options element was dom node, give it

### PR DESCRIPTION
**Pull request by suhaotian**

### CODE REVIEW

**Comment by sarcadass** [comment]
Can you also commit the builded files please (after modifying the lib, run `gulp`).
The builded files you should commit are:
* `dist/granim.js`
* `dist/granim.min.js`
* `docs/assets/js/vendor/granim.min.js`

Can you also modify the API page:
* `options.element` **Type** = String or HTMLCanvasElement
* `options.element` **Description**= A CSS selector for the `<canvas>` element or the  `HTMLCanvasElement` itself (e.g. `'#granim-canvas'` or `document.querySelector('#granim-canvas')`) that will be used for the gradient animation.

Thank you for the contribution.

**Comment by suhaotian** [comment]
Thank you !

**Comment by sarcadass** [comment]
The HTML for the docs is builded from \*.pug files located in `docs/assets/pug/*.pug`.
You have to modify the source file (`docs/assets/pug/api.pug:50`) then run `gulp buildDoc`.
If you don't, your modifications will be overwritten in the next build. (see the commentary I have written on #8).

Then you will have to commit:
* `docs/assets/pug/api.pug` -> source file
* `docs/api.html` -> builded file

Everything should be fine after that :).
Can you do the modifications ?

**Comment by suhaotian** [comment]
thank you..

**Comment by pranaygp** [comment]
@suhaotian It would be helpful if your git commits were more descriptive

**Comment by suhaotian** [comment]
I learn a lot to be a good contributor. thank you!

**Comment by sarcadass** [comment]
@suhaotian can you redo this PR in only one commit with a commit message like "**Add option to give HTMLCanvasElement as an options.element**".
This will be great :smile:, thank you.

**Comment by gridsystem** [comment]
@sarcadass this strikes me as something worth implementing?

**Comment by pranaygp** [comment]
@gridsystem this is definitely worth implementing. We're waiting for a response from @suhoitan. If someone else wants to take a Stab at it, that would work as well :)

**Comment by suhaotian** [comment]
@sarcadass My english is poor, you can change one line and commit 😄 . thank you.

**Comment by pranaygp** [comment]
@suhaotian that's understandable. No worries. @sarcadass, I'll continue working with integrating this PR since it seems to be pretty important

**Pull request merged**
